Script Start at : Tue Aug 22 13:07:10 2017


Going to Test  ['init', '1', 'discover']
passed wrong command line arguments
Traceback (most recent call last):
  File "run.py", line 229, in <module>
    
Exception: Error: you have passed wrong command line arguments['init', '1', 'discover']
